---
stages:
  - build
  - test
  - notify

build:
  stage: build
  tags:
    - api-tests
  script:
    - ./mvnw install

test:
  stage: test
  tags:
    - api-tests
  script:
    - ./mvnw clean verify
  artifacts:
    paths:
      - target/CucumberReport/cucumber-html-reports

telegram:
  stage: notify
  image: curlimages/curl:latest
  script:
    - echo "TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN"
    - echo "TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID"
    - 'curl -s --request POST --url
      "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" --header
      "Content-Type: application/json" --data-raw
      "{\"chat_id\":\"$TELEGRAM_CHAT_ID\",\"text\":\"GitLab CI/CD pipeline
      $CI_PIPELINE_ID for $CI_PROJECT_PATH has $CI_COMMIT_SHA status
      $CI_JOB_STATUS.\",\"disable_notification\": false}"'
